namespace DLS_Backend.Models;

/// <summary>
/// User model for the database
/// </summary>
/// <param name="id">unique identifier, generated by MSSQL</param>
/// <param name="guid">unique identifier, generated by Frontend</param>
/// <param name="first_name">Users first name</param>
/// <param name="last_name">Users last name</param>
/// <param name="password">Users hashed password</param>
/// <param name="created_at">Timestamp generated by MSSQL</param>
/// <param name="email">Users Email</param>
public partial class User
{
    public int id { get; set; }
    public Guid guid  { get; set; }
    public DateTime? created_at { get; set; }
    public ICollection<UserInfo> UserInfos { get; set; }
    public UserTombstone UserTombstone { get; set; }
    
}


