namespace DLS_Backend.Models;

/// <summary>
/// User model for the database
/// </summary>
/// <param name="id">unique identifier, generated by MSSQL</param>
/// <param name="guid">unique identifier, generated by Frontend</param>
/// <param name="first_name">Users first name</param>
/// <param name="last_name">Users last name</param>
/// <param name="password">Users hashed password</param>
/// <param name="created_at">Timestamp generated by MSSQL</param>
/// <param name="email">Users Email</param>
public partial class User
{
    public int id { get; set; }
    
    public Guid guid  { get; set; }

    public string first_name { get; set; } = null!;
    
    public string last_name { get; set; } = null!;

    public string password { get; set; } = null!;
    
    public DateTime? created_at { get; set; }

    public string email { get; set; } = null!;

    // Add UserInfoSnapshot property
    public UserInfo UserInfoSnapshot { get; set; }
}

/// <summary>
/// Register request model
/// </summary>
/// <param name="first_name">Users first name</param>
/// <param name="last_name">Users last name</param>
/// <param name="email">Users email</param>
/// <param name="password">Users hashed password</param>
public class RegisterRequest
{
    public string first_name { get; set; }
    public string last_name { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public Guid guid { get; set; }
}

/// <summary>
/// Login request model
/// </summary>
/// <param name="email">Users email</param>
/// <param name="password">Users hashed password</param>
public class LoginRequest
{
    public string email { get; set; }
    public string password { get; set; }
}
