name: .NET Core CI

on:
  push:
    branches: [ development, main]
  pull_request:
    branches: [ development, main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    
    services:
      
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: --name rabbitmq --hostname rabbitmq
      
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433  # Default SQL Server port
        options: >-
          --name=mssql


    steps:
      - uses: actions/checkout@v2
        
      

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.203'  # Ensure this version matches your project requirements
          
      - name: Check Encoded DB Password
        run: echo "${{ secrets.DB_PASSWORD }}" | sha256sum
      - name: Check Encoded DB User
        run: echo "${{ secrets.DB_USER }}" | sha256sum


      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RABBITUSER: ${{ secrets.RABBITUSER }}
          RABBITPW: ${{ secrets.RABBITPW }}
          RABBITURL: ${{ secrets.RABBITURL }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_BACKEND: ${{ secrets.DB_BACKEND }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FRONTENDURL: ${{ secrets.FRONTENDURL }}
          GITHUB_ACTIONS: true
        
        run: dotnet test --no-restore --verbosity normal