name: .NET Core CI

on:
  push:
    branches: [ development, main]
  pull_request:
    branches: [ development, main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
      
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup environment variables
        run: |
          echo "DB_SERVER=${{ secrets.INTERNAL_SERVER }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Start MSSQL with Custom Health Check
        run: |
          HEALTH_CMD="/opt/mssql-tools/bin/sqlcmd -Q 'SELECT 1' -S \$DB_SERVER -U \$DB_USER -P \$DB_PASSWORD -b || exit 1"
          docker run --name mssql_custom \
            --env ACCEPT_EULA=Y --env SA_PASSWORD=\$DB_PASSWORD \
            --publish 1433:1433 \
            --health-cmd="\$HEALTH_CMD" \
            --health-interval=10s --health-timeout=5s --health-retries=3 \
            --detach \
            mcr.microsoft.com/mssql/server:2019-latest

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.203'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RABBITUSER: ${{ secrets.RABBITUSER }}
          RABBITPW: ${{ secrets.RABBITPW }}
          RABBITURL: ${{ secrets.RABBITURL }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_BACKEND: ${{ secrets.DB_BACKEND }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FRONTENDURL: ${{ secrets.FRONTENDURL }}
        
        run: dotnet test --no-restore --verbosity normal