name: .NET Core CI

on:
  push:
    branches: [ development, main]
  pull_request:
    branches: [ development, main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - uses: actions/checkout@v2
        
      # Start up sqlserver        
      - run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=${{ secrets.DB_PASSWORD }}" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.203'  

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RABBITUSER: ${{ secrets.RABBITUSER }}
          RABBITPW: ${{ secrets.RABBITPW }}
          RABBITURL: ${{ secrets.RABBITURL }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_BACKEND: ${{ secrets.DB_BACKEND }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FRONTENDURL: ${{ secrets.FRONTENDURL }}
          GITHUB_ACTIONS: true
        
        run: dotnet test --no-restore --verbosity normal